#!/bin/bash

# Scale deployment
kubectl scale deployment messaging-app --replicas=3

# Verify multiple pods
kubectl get pods

# Load test with wrk (example, adapt the URL)
wrk -t4 -c100 -d10s http://$(minikube ip):<nodeport-or-ingress-path>

# Monitor resource usage
kubectl top pods
