apiVersion: v1
kind: Service
metadata:
  name: messaging-app-service
spec:
  selector:
    app: messaging-app
    version: green   # Change to 'blue' to switch back
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000