pipeline {
    agent any

    environment {
        IMAGE_NAME = 'yourdockerhubusername/messaging_app'
        TAG = 'latest'
    }

    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/yourusername/alx-backend-python.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('messaging_app') {
                    sh "docker build -t $IMAGE_NAME:$TAG ."
                }
            }
        }

        stage('Login to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh 'echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin'
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                sh "docker push $IMAGE_NAME:$TAG"
            }
        }
    }
}
