#!/bin/bash

# Apply both deployments and switch service
kubectl apply -f messaging_app/blue_deployment.yaml
kubectl apply -f messaging_app/green_deployment.yaml
kubectl apply -f messaging_app/kubeservice.yaml

# Check logs
kubectl get pods
kubectl logs -l app=messaging-green
